---
- name: Converge
  hosts: all
  vars:
    nvm_users:
      - name: "lorem"
        rc_file: ".zshrc"
      - name: "ipsum"
    nvm_rc_modify: true

  tasks:
    - name: Run ansible-role-nvm for each user.
      include_role:
        name: "ansible-role-nvm"
      vars:
        nvm_user: "{{ item }}"
      loop: "{{ nvm_users }}"
